import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import Navbar from './navbar'
import { Suspense } from 'react'
import AuthProvider from './auth/provider'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['200', '400']
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={roboto.className}>
        <AuthProvider>
        <Navbar />
        <main className='p-5'>
          {/* <Suspense fallback={<p>Loading the content...!</p>}> */}
              {children}
          {/* </Suspense> */}
        </main>
        </AuthProvider>
      </body>
    </html>
  )
}
